name = "mail-h"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

# 仅用于 H 仓库 / Cloudflare 项目
# Deploy command: npx wrangler deploy -c wrangler.h.toml
# 请把下面的 database_id / id 换成 H 环境自己的 D1、KV ID

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "cloud-mail-h"
database_id = "82ee5a76-684e-4100-9a97-8cee675bb735"

[[kv_namespaces]]
binding = "kv"
id = "1e2b2007f9b1479196135e2091933536"

#[[r2_buckets]]
#binding = "r2"
#bucket_name = ""

[[send_email]]
name = "email"

[ai]
binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 * * * *"]

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
