name = "mail-330"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

# 仅用于 mail-330 仓库 / Cloudflare 项目
# Deploy command: npx wrangler deploy -c wrangler.mail-330.toml

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "cloud-mail"
database_id = "b8df9820-335f-4642-b866-5984df9510fb"

[[kv_namespaces]]
binding = "kv"
id = "dfc2867e5cca4a478526c277b5c61605"

#[[r2_buckets]]
#binding = "r2"
#bucket_name = ""

[[send_email]]
name = "email"

[ai]
binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 * * * *"]

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
